Update docs on crypto details
theupdateframework/tuf pull request #1054
Opened 2020-06-17 15:20 UTC by jku

The specifics on crypto dependencies are out of date in a few places: fix setup.py comments and Tutorial.

Obviously this PR reflects my understanding of the situation -- and I'm a newbie here so I may have misunderstood. Review is welcome.

There's a potential additional fix in the Tutorial section that I'm not sure about:

> Which cryptography library to use is determined by the default, or user modified, settings in settings.py

This seems false or misleading -- only hash algorithms can be selected in settings and the signature algorithm selection is done when keys are generated, right?

2020-06-18 09:00 UTC, lukpueh reviewed
Many thanks for taking the time to research this and fixing the outdated docs, it is highly appreciated, @jku!

To add some context, @awwad and I compiled a list of docs issues a while ago, which can be found in #808. I fixed many of the tutorial-related issues in #775, but did focus on the code snippets. The accompanying text still requires a larger overhaul (as noted in item one of https://github.com/theupdateframework/tuf/issues/808#issuecomment-487596129). 

So I'm very happy about contributions like this one!  Let me know if you are interested in addressing my comments below, otherwise we can do this in a follow-up PR.

2020-06-18 09:00 UTC, lukpueh commented on setup.py
> +  $ pip install securesystemslib[crypto,pynacl]
IIRC `securesystemslib` with `crypto` and `pynacl` extras must be installed **before** `tuf`. The other way around pip will see securesystemslib as already installed (albeit w/o the extras) and just skip it. The ["Install with More Cryptographic Flexibility" section in the installation guide](https://github.com/theupdateframework/tuf/blob/develop/docs/INSTALLATION.rst#install-with-more-cryptographic-flexibility) has got this right.

Looking at the full docstring here I wonder if it isn't just better to point to the installation guide, for the sake of docs deduplication. Also, the `setup.py` commands don't seem particularly useful.

What do you think, @jku?

2020-06-18 09:00 UTC, lukpueh commented on docs/TUTORIAL.md
>  settings in [settings.py](../tuf/settings.py).
You are absolutely right, this setting was moved from TUF to securesystemslib, when securesystemslib was forked off of TUF, and has been removed from there when PyCrypto as alternative to cryptography was dropped.
Would you mind removing the sentence?

I would say the line above is still true as we do support multiple algorithms (rsa, ecdsa and ed25519) and multiple libraries (OpenSSL/cryptography for rsa and ecdsa, and libsodium/PyNacl  for ed25519, plus a pure python implementation for ed25519 signature verification).

2020-06-18 09:00 UTC, lukpueh commented on docs/TUTORIAL.md
> +format. Private keys are encrypted and passphrase-protected (strengthened with
Do you think it might be worth informing the reader that the snippet in this tutorial require both RSA and Ed25519 signing capabilities, and thus TUF should be installed with [full crypto support](https://github.com/theupdateframework/tuf/blob/develop/docs/INSTALLATION.rst#install-with-more-cryptographic-flexibility)?

2020-06-18 09:25 UTC, jku commented
> Let me know if you are interested in addressing my comments below, otherwise we can do this in a follow-up PR.

I'm leaving computers for a few days to celebrate midsummer in a moment but we can leave it open and I can tweak the PR next week

2020-06-18 09:30 UTC, lukpueh commented
Thanks and happy midsummer!

2020-06-18 09:35 UTC, jku commented on setup.py
> +  $ pip install securesystemslib[crypto,pynacl]
> The other way around pip will see securesystemslib as already installed (albeit w/o the extras) and just skip it

I don't think this is true on current pip version at least: 

```
$ pip list | grep securesystemslib
securesystemslib    0.15.0
$ python3 -c "import nacl"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'nacl'
$ pip install securesystemslib[pynacl]
...
Successfully installed pynacl-1.4.0
$ python3 -c "import nacl"
$ 

```

2020-06-18 09:49 UTC, lukpueh commented on setup.py
> +  $ pip install securesystemslib[crypto,pynacl]
Oh cool, then I either misremembered or this was changed in a recent release. :)

2020-06-22 11:03 UTC, jku commented on docs/TUTORIAL.md
> +format. Private keys are encrypted and passphrase-protected (strengthened with
yes, done

2020-06-22 11:06 UTC, jku commented
I did not remove the install examples from setup.py yet: Replacing them with a git url (like https://github.com/theupdateframework/tuf/blob/develop/docs/INSTALLATION.rst) in  released/installed files feels unclean... but I can do it if needed.

Other comments resolved.

2020-06-22 15:07 UTC, lukpueh requested changes
Thanks for the updates! I have one minor request. Then we can merge.

2020-06-22 15:07 UTC, lukpueh commented on docs/TUTORIAL.md
> +[installation Instructions](INSTALLATION.rst#install-with-more-cryptographic-flexibility)
Minor nit: I'd write "Installation Instructions" or "installation instructions" :)

2020-06-23 08:06 UTC, jku commented on docs/TUTORIAL.md
> +[installation Instructions](INSTALLATION.rst#install-with-more-cryptographic-flexibility)
oops, fixed

2020-06-23 10:00 UTC, lukpueh approved these changes
🎉

2020-06-23 10:00 UTC, merged