1080
theupdateframework/tuf pull request #1102
Opened 2020-08-06 11:43 UTC by MVrachev

**Fixes issue #**: https://github.com/theupdateframework/tuf/issues/1080

**Description of the changes being introduced by the pull request**:
Currently, if the repository is consistent_snapshot,
Updater will prefix the target filename with the hash
when constructing the download URL.
For some adopters of TUF (like Warehouse) this is not wanted
(warehouse target file paths are "consistent",
even if the filenames are not).

For example, Warehouse doesn't follow what tuf
(the reference implementation and specification) advice for naming
consistent filenames, which is to prefix the filename with the hash
of the files contents.
However, the target filenames it does use are consistent,
only the hash is part of the target's file path
not the target's file name.

**Please verify and check that the pull request fulfills the following
requirements**:

- [ ] The code follows the [Code Style Guidelines](https://github.com/secure-systems-lab/code-style-guidelines#code-style-guidelines)
- [ ] Tests have been added for the bug fix or new feature
- [ ] Docs have been added for the bug fix or new feature

2020-08-07 09:04 UTC, MVrachev commented
I decided to add `use_existing_hash_prefixes` argument to the `updater.download_target()` function instead as an argument to the `__init__` function for the Updater because `updater.download_target()` is really the only place where this argument is needed.
Plus, this made it easier for testing.

2020-08-10 07:07 UTC, jku requested changes
Thanks! I have comments mostly on phrasing plus a question on the test implementation

2020-08-10 07:07 UTC, jku commented on tests/test_updater.py
> +    self.assertTrue(os.path.exists(download_filepath))
How does the test work without any changes in the test data? Does the non-prefixed version exist on fileserver already?

If both versions exist on the server, maybe we should make sure only one does (for at least one download with each setting) -- otherwise we don't really know what we're downloading... or am I being overly cautious here?

2020-08-10 07:07 UTC, jku commented on tuf/client/updater.py
> +      use_existing_hash_prefixes=False):
I think putting the argument in this function (as opposed to Updater initializer) is fine. The name feels a bit off however: 
* `use_existing_hash_prefixes` might not be even technically correct (as Updater does not really know _why_ hash prefixed names are not used)
* the name does not help the Updater user understand what the argument does

The second point is the important one. Would `prefix_filename_with_hash=True` be too long?

2020-08-10 07:07 UTC, jku commented on tuf/client/updater.py
> +        Default is False.
Can you make it clear that the prefix is added to the _download query_ made to the server, not to the filename that's saved to destination_directory. 

Mentioning "consistent snapshot" is good but I fear most readers will not understand what it means... How about adding another sentence like this: 

> This should be set to True when the served target filenames are not prefixed with hashes (in this case the server uses other means to ensure snapshot consistency).

2020-08-10 11:23 UTC, MVrachev commented on tests/test_updater.py
> +    self.assertTrue(os.path.exists(download_filepath))
No, it's a good question and I should leave a comment somewhere about this.
I investigated and on line 1291 in the same file, same tests where writeall is called with consistent snapshot = True: https://github.com/theupdateframework/tuf/blob/a088b68fa7cb026eaf06dd77c95f13bce614ed2c/tests/test_updater.py#L1291
creates three files in the temporary repository directory which are in the format `HASH.Filename.ext`.

2020-08-10 13:32 UTC, MVrachev commented on tuf/client/updater.py
> +      use_existing_hash_prefixes=False):
No, it's not too long, on the contrary - it's one character less :D.

I agree that this argument name doesn't give good information for the user. I have been thinking a lot about how to call it.
`prefix_filename_with_hash` sounds okay.

2020-08-10 13:39 UTC, MVrachev commented on tuf/client/updater.py
> +        Default is False.
A good point.
When you pointed it out I remembered I was a little confused about what file is saved on the backend with the hash prefix or without it.

2020-08-10 13:54 UTC, jku commented on tests/test_updater.py
> +    self.assertTrue(os.path.exists(download_filepath))
:+1: so then the question is, should we be stricter in the test? I'm thinking of something like us mixing up True and False in handling this: this test would not notice that...

2020-08-17 16:36 UTC, MVrachev commented
I updated my pr adding the necessary explanations in the test and changing the variable name.

2020-08-18 13:59 UTC, joshuagl approved these changes
This looks like a nice clean change, thanks @MVrachev.

@jku could you take another look to ensure it suits your needs and your prior comments have been addressed?

2020-08-18 13:59 UTC, joshuagl commented on tests/test_updater.py
> +    # the served target file is not prefixed.
Avoid talking in the first person in code comments.
```suggestion
    # Remove the files with the hash digest prefix to ensure that
    # the served target file is not prefixed.
```

2020-08-18 16:21 UTC, jku approved these changes
LGTM, thanks Martin.

(Btw, the Travis timeout happened in a place where we get server output: It is using a port that is used already! Good info but not related to this bug)

2020-09-02 15:28 UTC, merged

2020-09-02 15:28 UTC, joshuagl commented
Thanks for the patches @MVrachev and for the review @jku

2020-09-02 15:28 UTC, joshuagl commented
Thanks for the patches @MVrachev and for the review @jku