Refactor get metadata file
theupdateframework/tuf pull request #1205
Opened 2020-11-10 16:00 UTC by MVrachev

**Description of the changes being introduced by the pull request**:

Currently, the `_get_metadata_file()` from `tuf/client/updater.py` is really large 
and does too many things and some of them partially.
Right now, it validates the specification version and the metadata version in it,
but doesn't validate if the metadata has expired or if the signature could be trusted.
So, it's partially validating the metadata file and at the same time calling 
`_verify_metadata_file()` from updater.py for the rest of the work which doesn't make
sense.

It's logically better if we move the validation of the specification
and the metadata version in separate functions which would
be then called in ` _verify_metadata_file()` and that way move all of the validation
will be done in ` _verify_metadata_file()`.

**Please verify and check that the pull request fulfills the following
requirements**:

- [ ] The code follows the [Code Style Guidelines](https://github.com/secure-systems-lab/code-style-guidelines#code-style-guidelines)
- [ ] Tests have been added for the bug fix or new feature
- [ ] Docs have been added for the bug fix or new feature

2020-11-10 16:03 UTC, MVrachev commented on tests/test_endless_data_attack.py
> +        self.assertTrue(isinstance(mirror_error, tuf.exceptions.InvalidMetadataJSONError))
Now, when all of the validation is done in `_verify_metadata_file` another type of exception will
be thrown for `timestamp.json` and thus I had to change it here.

2020-11-10 16:08 UTC, MVrachev commented
While I was working on that, I thought that maybe it's not so logical to verify the metadata file by calling `_verify_metadata_file()` in `_get_metadata_file`.

`_get_metadata_file` is called in `_update_metadata` and I think it makes sense to call separately `_verify_metadata_file()` after calling `_get_metadata_file` inside the `_update_metadata` function.

I didn't change it here, because I wanted to hear an opinion on that first.

2020-11-23 09:39 UTC, jku requested changes
There's probably a debate here: do we want to do fixes like this now, does this make e.g. Teodoras work more difficult?

Personally I think there's value in this and the idea is correct: it makes the core update loop easier to read and makes us find issues in it. That said, the update loop feels brittle: let's make sure we do not break it... I left comments in code.

I also think we should try to fix the comments and logging when we touch them (make sure they're correct, useful and not too verbose) -- did not leave comments on those yet

2020-11-23 09:39 UTC, jku commented on tuf/client/updater.py
>      <Exceptions>
Documented exceptions are unlikely to still be complete after these changes, please check

2020-11-23 09:39 UTC, jku commented on tests/test_endless_data_attack.py
> +        self.assertTrue(isinstance(mirror_error, tuf.exceptions.InvalidMetadataJSONError))
this is a sign of an API change -- maybe a good one but it should still be a conscious and documented decision. I assume it happens because the initial `load_json_string()` result is now caught when previously it was not?

Which one is buggy (old or new way) and why?

2020-11-23 09:39 UTC, jku commented on tuf/client/updater.py
> +              version_downloaded, current_version)
This check (`version_downloaded < current_version`) is actually not consistent with the docstring or the comment above... what should really happen when `version_downloaded == current_version`?

I realize this inconsistency exists in 'develop' right now, but I'd like us to either fix the comment & docstring or file an issue while we do this.

2020-11-23 09:50 UTC, MVrachev commented
> There's probably a debate here: do we want to do fixes like this now, does this make e.g. Teodoras work more difficult?

It's best if @sechkova could look into those changes and give an opinion as well.
I need those changes for https://github.com/theupdateframework/tuf/pull/1214.
I need to be able to abstract the spec and version verifications so that they could be reused when verifying older versions
of root.json.

> I also think we should try to fix the comments and logging when we touch them (make sure they're correct, useful and not too verbose) -- did not leave comments on those yet

Yes, a good reminder.
Will have a look at the comments again.
Please leave more comments if you want me to change a specific comment or line.

2020-11-23 13:11 UTC, sechkova commented
I am by no means against improving the code given that this is the currently used version and the rework is only just a dream ... yet.

2020-11-23 14:05 UTC, jku commented
> Please leave more comments if you want me to change a specific comment or line.

From memory: expected_version argument would have the typing hint "Optional[int]" but the possibility of None is not documented in several function docstrings. Both `_validate_*()` functions are quite long considering how little they do: comments and logging are so verbose.

2020-11-25 16:11 UTC, joshuagl commented on tuf/client/updater.py
> +        of the 'metadata_role' file downloaded.
Or `None`?

2020-11-25 16:11 UTC, joshuagl commented on tuf/client/updater.py
> +    # Verify that the downloaded version is at least greater
Below we're checking that the current version is not less (<) than the current version, which contradicts this comment (which implies <=).

2020-11-25 16:12 UTC, joshuagl commented on tuf/client/updater.py
> +              version_downloaded, current_version)
Let's fix the comment and docstring.

2020-12-04 15:08 UTC, MVrachev commented on tests/test_endless_data_attack.py
> +        self.assertTrue(isinstance(mirror_error, tuf.exceptions.InvalidMetadataJSONError))
I think the old one is buggy and not clear.
I catch it in `_verify_metadata_file` and instead throw a more concrete exception.
I will leave comments on both places: where I catch it and in the test.

2020-12-04 17:31 UTC, MVrachev commented on tuf/client/updater.py
> +    # Verify that the downloaded version is at least greater
In the spec, it says:
```
The version number of the trusted timestamp metadata file, if any, MUST be less than or equal 
to the version number of the new timestamp metadata file. 
If the new timestamp metadata file is older than the trusted timestamp metadata file, discard it, 
abort the update cycle, and report the potential rollback attack.
```
The same applies to `Root` and `Snapshot`.

2020-12-04 17:33 UTC, MVrachev commented on tuf/client/updater.py
> +              version_downloaded, current_version)
In the spec, it says:
```
The version number of the trusted timestamp metadata file, if any, MUST be less than or equal 
to the version number of the new timestamp metadata file. 
If the new timestamp metadata file is older than the trusted timestamp metadata file, discard it, 
abort the update cycle, and report the potential rollback attack.
```
The same applies to `Root` and `Snapshot`.

So, I will change the above comment and docstring to  
```
Verify that the downloaded version is equal or 
greater than the locally available.

2020-12-07 14:28 UTC, MVrachev commented
Updated this pr according to @joshuagl and @jku comments.
Had to rebase because there were changes in `tuf/client/updater.py`.

2020-12-16 13:36 UTC, MVrachev commented
After a discussion with @joshuagl, I added the last commit to simplify some of the comments and the way we check for spec conformance.

2021-01-28 11:49 UTC, closed without merging