WIP: Mirrors redesign
theupdateframework/tuf pull request #1331
Opened 2021-04-06 09:31 UTC by sechkova

Addresses: #1307

Description of the changes being introduced by the pull request:

Regrouping of client-related modules:

- moved components related to file download inside the `client_rework` directory
- applied black and isort on the modules with the old code style
-  `download.py` is deleted and its functionality is merged with `mirrors.py` which is now `mirrors_download.py`
- code is wrapped in `Mirrors` class

**Please verify and check that the pull request fulfills the following
requirements**:

- [ ] The code follows the [Code Style Guidelines](https://github.com/secure-systems-lab/code-style-guidelines#code-style-guidelines)
- [ ] Tests have been added for the bug fix or new feature
- [ ] Docs have been added for the bug fix or new feature

2021-04-07 14:33 UTC, MVrachev requested changes
The only questionable choice I see is the one with the naming of the class `Mirrors`.

Of the 6 methods in the `Mirrors` class, 4 of them have the word `download` in them.
I think this is a good sign that the class name is better to be just `Downloader`.
Yes, for download were using mirrors, but that seems like an API detail giving
that we don't have a non-mirrors downloader class.

One would say that `Fetcher` and `Downloader` are close names but calling the class
`Mirrors` just hides that proximity.  

Other than that, I have some small comments, but nothing too serious.

2021-04-07 14:33 UTC, MVrachev commented on tuf/client_rework/mirrors.py
>  # division.  Example:  print 'hello world' raises a 'SyntaxError' exception.
Do we want to copy those comments and the future imports too?
I know we are going to remove them when resolving this issue https://github.com/theupdateframework/tuf/issues/1297,
but do we want to add them in new files as well?

2021-04-07 14:33 UTC, MVrachev commented on tuf/client_rework/mirrors.py
> +    def _get_list_of_mirrors(self, file_type, file_path):
Do you plan to add type annotations to the old functions as well which were moved or only on the newly added ones?

2021-04-07 14:33 UTC, MVrachev commented on tuf/client_rework/mirrors.py
> +from tuf.requests_fetcher import RequestsFetcher
I think you should import the `FetcherInterface` as well, because later on in the `Mirrors.__init__` you use the "FetcherInterface" as a type annotation.
Locally I see warnings because of this.

2021-04-07 14:33 UTC, MVrachev commented on tuf/client_rework/mirrors_download.py
> +            # the warning. This should be reviewed in the future still.
Maybe add a `TODO` if you expect us to review this in the future?

2021-04-08 07:49 UTC, jku commented on tuf/client_rework/fetcher.py
> +# Imports
Nit: I think these _Imports/Classes_ comments are not useful.

2021-04-20 14:04 UTC, sechkova commented
Closing this one in favour of #1341 and #1352

2021-04-20 14:05 UTC, closed without merging