Add a method of Signed metadata class returning information about metadata expiration
theupdateframework/tuf pull request #1347
Opened 2021-04-12 11:05 UTC by avelichka

Adds the **is_expired** method to the **Signed** metadata class that checks the **expires** attribute against a reference time and returns information about metadata expiration 

Signed-off-by: Velichka Atanasova <avelichka@vmware.com>

Please fill in the fields below to submit a pull request.  The more information
that is provided, the better.

Fixes #1305

**Description of the changes being introduced by the pull request**:

**Please verify and check that the pull request fulfills the following
requirements**:

- [ ] The code follows the [Code Style Guidelines](https://github.com/secure-systems-lab/code-style-guidelines#code-style-guidelines)
- [ ] Tests have been added for the bug fix or new feature
- [ ] Docs have been added for the bug fix or new feature

2021-04-13 07:28 UTC, jku requested changes

2021-04-13 07:28 UTC, jku commented on tests/test_api.py
> +        self.assertEqual(is_exired, True)
just a nit but: typo in is_expired

2021-04-13 07:28 UTC, jku commented on tuf/api/metadata.py
> +    def is_expired(self, reference_time=datetime.now()) -> bool:
reference_time should be type annotated, no? Also more importantly this looks like a [mutable default argument](https://docs.python-guide.org/writing/gotchas/#mutable-default-arguments) and may be a bug

2021-04-13 08:10 UTC, sechkova commented on tuf/api/metadata.py
> +    def is_expired(self, reference_time=datetime.now()) -> bool:
In addition, `datetime.now()` returns local time and date. The [recommended way](https://docs.python.org/3/library/datetime.html#datetime.datetime.utcnow) to get UTC time seems to be:
`datetime.now(timezone.utc)`

2021-04-13 10:58 UTC, jku commented on tuf/api/metadata.py
> +    def is_expired(self, reference_time=datetime.now()) -> bool:
This is a good point ...  but I _think_ our expiry datetimes are timezone-naive so datetime.utcnow() might actually be what we want (or alternatively we should be creating expiry datetime as timezone-aware)

2021-04-13 11:04 UTC, jku commented on tuf/api/metadata.py
> +    def is_expired(self, reference_time=datetime.now()) -> bool:
well the tests seem happy so maybe I was wrong and our expiry datetime is not naive?

2021-04-13 11:05 UTC, avelichka commented on tuf/api/metadata.py
> +    def is_expired(self, reference_time=datetime.now()) -> bool:
Ops, I've just pushed a commit with what @sechkova suggested but I will correct it if needed.
@jku, I've addressed your comments in separate commits that I'm going to squash as soon as you approve and review the changes.

2021-04-14 08:03 UTC, jku requested changes
Looks good, except for the docstring format (TUF is full of the format you used but we're trying to move to standard docstrings). I _think_ I have a suggestion that's correct below... 

Feel free to squash all of this into a single commit (btw, commit message titles preferred under 50 characters).

2021-04-14 08:03 UTC, jku commented on tuf/api/metadata.py
> +        """
Thanks this helps... but it's the old style doc format which we're hoping to not use in api/

```suggestion
        """Checks metadata expiration against a reference time.

        Args:
            reference_time: Optional; The time to check expiration date against.
                A naive datetime in UTC expected.
                If not provided, checks against the current UTC date and time.

        Returns:
            True if expiration time is less than the reference time.
        """
```

I think this matches the current style (https://google.github.io/styleguide/pyguide.html#383-functions-and-methods) ... but I've never used this style yet either so maybe @MVrachev or someone more familiar can confirm if this is what we want for new code?
In any case let's try to keep it to as few lines as possible.

2021-04-14 08:47 UTC, sechkova commented on tuf/api/metadata.py
> +        """
Looks good, should be ok with the new style.

2021-04-14 11:03 UTC, avelichka commented on tuf/api/metadata.py
> +        """
Thank you all for the comments! I believe I addressed all issues and pushed a squashed commit. I promise to carefully go through the guidelines again and to do better with observing best practices and recommendations next time :)

2021-04-15 11:49 UTC, jku approved these changes
Thank you

2021-04-16 05:49 UTC, merged