Remove max_length parameter from fetch
theupdateframework/tuf pull request #1519
Opened 2021-08-10 11:47 UTC by sechkova

Fixes #1502

**Description of the changes being introduced by the pull request**:

If a file has a bigger size than expected, RequestFetcher.fetch
downloads it up to max_length without any errors. Only the
consecutive hash check raises exception. A better behavior
in such case would be to raise a DownloadLengthMismatchError.

For this reason this PR:
- removes max_length from the fetch() definition,
- modifies download_file to check the downloaded length after
  each chunk and raise an error accordingly.

**Please verify and check that the pull request fulfills the following
requirements**:

- [ ] The code follows the [Code Style Guidelines](https://github.com/secure-systems-lab/code-style-guidelines#code-style-guidelines)
- [ ] Tests have been added for the bug fix or new feature
- [ ] Docs have been added for the bug fix or new feature

2021-08-16 06:40 UTC, jku reviewed
This breaks FetcherInterface API but the result looks like the API we should have made in the first place: it's a cleaner separation of duties and simplifies the fetcher implementation. LGTM in general.

Is it possible to make a test for the case you are fixing?

2021-08-16 06:40 UTC, jku commented on tuf/ngclient/fetcher.py
>                  )
is this now logged for every chunk on purpose?

2021-08-17 08:21 UTC, jku commented
> Is it possible to make a test for the case you are fixing?

It would make sense to add tests for ngclient fetcher: not just the ones that already exist for fetcher in legacy code but for download_bytes() and download_file() -- where testing this issue would make sense

2021-08-26 14:47 UTC, sechkova commented on tuf/ngclient/fetcher.py
>                  )
Not really ...

2021-08-27 11:17 UTC, sechkova commented
Added some tests, mostly copied from test_fetcher.py but modified for the implementation. There's some duplication, maybe unneeded ... 
Do we want to open another issue for testing the networking side of RequestsFetcher? I suppose we do.

2021-08-27 11:48 UTC, jku commented
> Do we want to open another issue for testing the networking side of RequestsFetcher?

What do you mean specifically -- this PR seems to test the complete RequestsFetcher surface? Obviously more tests doesn't hurt but it looks like coverage wise we're ok.

2021-08-27 12:20 UTC, sechkova commented
> What do you mean specifically -- this PR seems to test the complete RequestsFetcher surface? Obviously more tests doesn't hurt but it looks like coverage wise we're ok.

We still miss tests for `urllib3.exceptions.ReadTimeoutError` (and `sleep` but we want to remove it anyway) at least from the coverage report ... I should just add it to this PR

2021-08-27 13:21 UTC, sechkova commented
That's what I could do with the available test utils: 0f19815

2021-08-30 09:22 UTC, jku commented
This looks fine otherwise but I refuse to accept a test that takes 5 seconds to run. I can accept either not testing slow retrieval here or making the test runtime more reasonable

2021-08-30 09:23 UTC, jku requested changes
This looks fine otherwise but I refuse to accept a test that takes 5 seconds to run. I can accept either not testing slow retrieval here or making the test runtime more reasonable

2021-08-30 09:26 UTC, jku commented
Actually I do have a question: is it necessary to setup and teardown the server for each individual test?

2021-08-30 09:40 UTC, sechkova commented
> Actually I do have a question: is it necessary to setup and teardown the server for each individual test?

Hmm ... no, I don't think so ... let me fix it.

2021-08-30 09:42 UTC, sechkova commented
> This looks fine otherwise but I refuse to accept a test that takes 5 seconds to run. I can accept either not testing slow retrieval here or making the test runtime more reasonable

I was kind of expecting it 😁 I'll remove the test and open an issue so that we do it properly (maybe tweak the current `slow_retreival_server.py`)

2021-08-30 13:38 UTC, sechkova commented
So test commits are squashed in a single one 35ef056:
- server creation is moved to `setUpClass`
- opened a separate issue for testing the read timeout

I think the test setup can be further improved since the temp data file can be created once per class too but currently `Modified_TestCase` overrides `setUp` only and does not work in class methods.

2021-08-31 11:18 UTC, jku approved these changes
I think the Fetcher change is correct, and the tests look like a good basic set of tests for Fetcher/RequestsFetcher.

Both of the last two test changes improve the test runtime about 10x: that looks ok now.

2021-09-01 14:27 UTC, merged