Add Key.from_securesystemslib_key
theupdateframework/tuf pull request #1520
Opened 2021-08-10 12:53 UTC by avelichka

The securesystemslib key dictionary representation includes
the private key in keyval. TUF key doesn't handle it in any way,
but considering that we allow unrecognized symbols in the format,
we should exclude the private key.
A call to securesystemslib.keys.format_keyval_to_metadata
with the default private=False would do exactly that.

Signed-off-by: Velichka Atanasova <avelichka@vmware.com>

Please fill in the fields below to submit a pull request.  The more information
that is provided, the better.

Fixes #1458

**Description of the changes being introduced by the pull request**:

**Please verify and check that the pull request fulfills the following
requirements**:

- [ ] The code follows the [Code Style Guidelines](https://github.com/secure-systems-lab/code-style-guidelines#code-style-guidelines)
- [ ] Tests have been added for the bug fix or new feature
- [ ] Docs have been added for the bug fix or new feature

2021-08-16 16:17 UTC, MVrachev commented
As someone who didn't read the issue solved by this pr, it was a little unclear why we need to remove
the private part of the securesystemslib key. I had to read Jussi's issue to understand the problem
Maybe you can modify your second sentence in your pr description and commit message like this:
```
TUF key doesn't handle it in any way,
but considering that we allow unrecognized symbols in the format,
we should exclude the private key otherwise this could lead to unexpected
behavior.
For example, those steps could lead to a mistake:
1. create a Metadata object with a root instance for Metadata.signed:
md = Metadata.from_file(<root_path>)
2. create a securesystemslib key:
sslib_key = generate_ed25519_key()
3. create a TUF Key using the dictionary representing the securesystemslib key:
key = Key.from_dict(sslib_key["keyid"], sslib_key)
4. add the new TUF key to the root instance
md.signed.add_key("root", key)
5. save the metadata back to a file by calling Metadata.to_file():
md.to_file("root_test.json")

this will result in a new "root_test.json" JSON file containing the private portion of a key.
```

Not sure if this will help, but a use case like this can highlight the issue without looking at the GitHub issue.
Otherwise, the code looks good to me.

PS: I tried the steps from 1 to 6 and they produce the expected result.

2021-08-24 07:46 UTC, jku requested changes

2021-08-24 07:46 UTC, jku commented on tuf/api/metadata.py
> +        )
this is interesting -- I was half expecting we'd have to make assumptions about keyval contents in this function but you found an sslib function that mostly does what you need... I think this looks reasonable except on the last line you add the whole key_dict (including the secret) as "unrecognised fields", oops. No need for unrecognised_fields here.

You _could_ modify the test so it looks for the secret in the serialized format of the key to be sure... but that sounds a bit much. Checking to_dict() output manually (to see that the above issue is fixed) should be fine.

2021-08-24 07:46 UTC, jku commented on tests/test_api.py
> +        self.assertFalse(private_key)
```suggestion
        self.assertFalse('private' in key.keyval.keys())
```
or do i miss something?

2021-08-26 12:41 UTC, avelichka commented on tuf/api/metadata.py
> +        )
Thaks, @jku! Addressed.

2021-08-26 12:41 UTC, avelichka commented on tests/test_api.py
> +        self.assertFalse(private_key)
Thaks, @jku! Addressed.

2021-08-30 09:17 UTC, jku approved these changes
Thanks, LGTM. I think this makes sense so all of our example code and repository code can easily create new keys and use them without complex code just to handle this issue.

The thing that makes me wonder about this is adding more and more functionality into Metadata API that the client does not need. We'll need to be careful not to overdo this (or figure out some RepositoryMixin classes or something ...)

2021-08-30 10:04 UTC, joshuagl commented
> The thing that makes me wonder about this is adding more and more functionality into Metadata API that the client does not need. We'll need to be careful not to overdo this (or figure out some RepositoryMixin classes or something ...)
> 

💯 Agree with this train of thought, metadata.py is very large.

2021-08-31 06:42 UTC, merged