Add python3.10 and fix test failures on python3.10
theupdateframework/tuf pull request #1628
Opened 2021-10-20 16:46 UTC by MVrachev

Fixes #1614

**Description of the changes being introduced by the pull request**:

Python 3.10 is released on October 4-th 2021 and it seems
logical to add support for it as it doesn't require any major effort
from the project.

For reference read:
https://www.python.org/downloads/release/python-3100/

I tried adding support for Python3.10 in https://github.com/theupdateframework/python-tuf/pull/1610.
Then, we had CI errors due to test failures: https://github.com/theupdateframework/python-tuf/pull/1610/checks?check_run_id=3861875325
The problem comes from the fact that we start a subprocess
executing simple_https_server.py, but then we fail to communicate the
message we expect from the server process to the main process actually
running the test. We expect our custom message to be the first line
printed from the server process, but instead, a deprecation warning is
printed first about the usage of ssl.wrap_socket(). Our custom message
is printed second.
As of Python 3.7 this function has been deprecated:
https://docs.python.org/3/library/ssl.html#ssl.wrap_socket and for
whatever the reason we didn't get a warning when using it before.

My fix does what is suggested in the warning and replaces the usage of
ssl.wrap_socket() by instantiating a ssl.SSLContext object and then
calling SSLContext.wrap_socket().
This removes the warning.

**Please verify and check that the pull request fulfills the following
requirements**:

- [ ] The code follows the [Code Style Guidelines](https://github.com/secure-systems-lab/code-style-guidelines#code-style-guidelines)
- [ ] Tests have been added for the bug fix or new feature
- [ ] Docs have been added for the bug fix or new feature

2021-10-20 16:48 UTC, MVrachev commented
I test locally and found that when you have Python 3.10 installed locally, then both 310 and 3.10 work when defining the new Python version in the `tox.ini` envlist and using it later with `tox -e`.
I think I prefer `3.10`.

2021-10-21 07:20 UTC, jku requested changes

2021-10-21 07:20 UTC, jku commented on tests/simple_https_server.py
> +httpd.socket = context.wrap_socket(httpd.socket)
Does this wrap_socket() not need `server_side=True`?

2021-10-21 07:20 UTC, jku commented on tox.ini
> +envlist = lint,py{36,37,38,39,3.10}
This does create an environment called `py3.10`, but the magic that sets up the correct interpreter doesn't understand the number (or just recognises the "3") so you just get a new environment with default python. `tox -e <envname>` should fail with InterpreterNotFound on a system that does not have that python installed.

2021-10-21 07:28 UTC, jku commented on .github/workflows/ci.yml
> +        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10"]
Format with untyped values bites developer, part 9000 :sob: 

I wonder how many people will independently fix this exact issue in the next year

2021-10-21 11:19 UTC, MVrachev commented on tox.ini
> +envlist = lint,py{36,37,38,39,3.10}
Ohh, okay. Fixing it.

2021-10-21 11:19 UTC, MVrachev commented on tests/simple_https_server.py
> +httpd.socket = context.wrap_socket(httpd.socket)
Strangely it works without it too but will add it as it's logical.

2021-10-21 11:34 UTC, MVrachev commented
@jku addressed your comments.

2021-10-21 11:40 UTC, jku approved these changes
Thank you

2021-10-21 11:40 UTC, merged