Update ngclient to skip visited nodes on delegation tree traversal
theupdateframework/tuf pull request #1683
Opened 2021-11-18 10:25 UTC by ivanayov

This change edits the ngclient `Updater` to traverse the delegation
tree on nodes, instead of edges in order to skip already visited
nodes.

For more detailed clarification, please review
theupdateframework/specification#177

Fixes #1528

Signed-off-by: Ivana Atanasova <iyovcheva@iyovcheva-a02.vmware.com>

- [x] The code follows the [Code Style Guidelines](https://github.com/secure-systems-lab/code-style-guidelines#code-style-guidelines)
- [n/a] Tests have been added for the bug fix or new feature
- [n/a] Docs have been added for the bug fix or new feature

2021-11-18 10:29 UTC, ivanayov commented
Testing the delegation tree traversal requires changes in the implementation that are not related to this change and as a major update of the tests is already in the process of writing, I'm pushing this change relying only on current tests and logic assumptions.

2021-11-18 13:16 UTC, sechkova requested changes
Unfortunately creating cyclic delegation graphs is not trivial yet both with old and new test code. I've been working on it #1641 ... so I'd say this is ok for now except for my comment below.

2021-11-18 13:16 UTC, sechkova commented on tuf/ngclient/updater.py
> +                visited_role_names.add(parent_role)
I don't think this is needed. We always start from "targets" and do a pre-order depth-first search, if the traversal code is correct, the parent is always visited before the child.

2021-11-19 09:17 UTC, sechkova approved these changes

2021-11-22 14:03 UTC, merged