Tests: add dump dir option and fix an error
theupdateframework/tuf pull request #1702
Opened 2021-12-01 19:19 UTC by MVrachev

**Description of the changes being introduced by the pull request**:

While running `python test_updater_with_simulator.py --dump` I noticed that when testing fishy role names
we write dump in an invalid file and an error was thrown:
`"PermissionError: [Errno 13] Permission denied: '/.json'"`
Given the context of this test, I think we can skip dumping role names.

Additionally, I noticed there are a couple of test files that don't support dumping of the repository
simulator state and I add support for that.

**Please verify and check that the pull request fulfills the following
requirements**:

- [ ] The code follows the [Code Style Guidelines](https://github.com/secure-systems-lab/code-style-guidelines#code-style-guidelines)
- [ ] Tests have been added for the bug fix or new feature
- [ ] Docs have been added for the bug fix or new feature

2021-12-02 08:10 UTC, jku commented
alternatively could sanitize the delegated rolename when writing the file like client does (`quoted_role = parse.quote(role, "")`)

2021-12-02 08:25 UTC, sechkova commented
Well it just happened that I did the same thing yesterday: dc908eee52dcf2b66dcd38eb54c972a2b3e17ec2
(without the part in test_updater_with_simulator.py)

2021-12-02 08:49 UTC, MVrachev commented
> 

@sechkova I am sorry it happened that way, I haven't read #1689 and didn't notice that. 
I will drop this commit and leave only the commit related to the error.

2021-12-02 09:14 UTC, sechkova commented
Bad timing on both sides 🤷 Can you have a look at my commit before dropping yours? Maybe I've missed something.

2021-12-02 10:24 UTC, MVrachev commented
> Bad timing on both sides 🤷 Can you have a look at my commit before dropping yours? Maybe I've missed something.

I just had a look and yours seems to cover what I did here, so don't worry.

2021-12-02 14:17 UTC, MVrachev commented
I updated the code by using what @jku suggested.
Additionally, the commit and pr descriptions were changed together with the pr title.

2021-12-08 09:14 UTC, jku requested changes
This commit does not do what the message says.

* It url encodes role names that do not need sanitizing (but does not url encode the delegated role names that could need it)
* Then it skips dumping metadata for roles that actually would need sanitizing if they were used as filenames?

2021-12-13 12:29 UTC, MVrachev commented
> This commit does not do what the message says.
> 
> * It url encodes role names that do not need sanitizing (but does not url encode the delegated role names that could need it)
> * Then it skips dumping metadata for roles that actually would need sanitizing if they were used as filenames?

I changed the code to dump the delegated roles and removed the code where I skipped dumping.

2021-12-13 12:29 UTC, jku approved these changes

2021-12-15 09:23 UTC, merged