Issue#1682/repository simulator fetch tracker
theupdateframework/tuf pull request #1704
Opened 2021-12-02 10:14 UTC by kairoaraujo

This commit implements a feature in Repository Simulator to
track the fetch calls to the metadata and targets. This feature was
mentioned in PR #1666 that generated issue #1682.
This commit adds ``RepositorySimulator.fetch_tracker``. It also changes
the ``tests/test_updater_consistent_snapshot.py`` to use the
``fetch_tracker`` instead of using mock.

It implements a ``dataclass`` that stores the calls to fetch metadata
(``_fetch_metadata``) in ``fetch_tracker.metadata`` and targets
(``_fetch_targets``) in ``fetch_tracker.targets``.

The fetch calls for metadata, and targets are stored as lists.

Signed-off-by: Kairo de Araujo <kdearaujo@vmware.com>

Please fill in the fields below to submit a pull request.  The more information
that is provided, the better.

Fixes  #1682

**Description of the changes being introduced by the pull request**:

**Please verify and check that the pull request fulfills the following
requirements**:

- [X] The code follows the [Code Style Guidelines](https://github.com/secure-systems-lab/code-style-guidelines#code-style-guidelines)
- [X] Tests have been added for the bug fix or new feature
- [ ] Docs have been added for the bug fix or new feature

2021-12-02 10:16 UTC, kairoaraujo reviewed
I am storing it as a ``tuple('role name', 'version')`` for metadata and ``tuple('target path', 'target hash')``. I am still in doubt about readability; maybe we should move it to a dictionary, then we don't need to rely on the code comments to understand it at the first code read.

2021-12-02 10:16 UTC, kairoaraujo commented on tests/repository_simulator.py
> +        self.fetch_tracker.targets.append((target_path, target_hash))
We append to the fetch_tracker.targets all fetch requests. Should we append-only successful ones?

2021-12-02 10:16 UTC, kairoaraujo commented on tests/repository_simulator.py
> +        self.fetch_tracker.metadata.append((role, version))
We append to the fetch_tracker.metadata all fetch requests. Should we append-only successful ones?

2021-12-02 16:02 UTC, sechkova requested changes
Thanks, the trackers look good, I think this is what we needed.
My comments are minor, related to types but also I think one check is missing. 

I was wondering if defining a dataclass (or two dataclasses for metadata and targets) instead of using tuples may simplify the expected calls lists. We can set default values and "typing" will be simpler but on the other hand instead of (root, 1) we'll have to write SomeCall(root, 1) ... so I am not sure about this. This is a way to say that I am looking for a second opinion, not requesting changes :grin:  We can keep it like this for now, maybe when more use cases come this choice we'll be more obvious.

2021-12-02 16:02 UTC, sechkova commented on tests/repository_simulator.py
> +    targets: list = field(default_factory=list)
```suggestion
    metadata: List[Tuple[str, Optional[int]]] = field(default_factory=list)
    targets: List[Tuple[str, Optional[str]]] = field(default_factory=list)
```

2021-12-02 16:02 UTC, sechkova commented on tests/test_updater_consistent_snapshot.py
> -                self._assert_targets_files_exist([info.path])
I think we want to keep this check?

2021-12-02 16:02 UTC, sechkova commented on tests/repository_simulator.py
> +    targets: list = field(default_factory=list)
I know my suggestion is ugly but if we want to be strict about types ... I guess it's fine until it appears only once.

2021-12-02 16:02 UTC, sechkova commented on tests/repository_simulator.py
> +        self.fetch_tracker.targets.append((target_path, target_hash))
We want to track the all requests coming from the client and I think this is the correct place.

2021-12-02 16:02 UTC, sechkova commented on tests/repository_simulator.py
> +        self.fetch_tracker: FetchCounter = FetchCounter()
```suggestion
        self.fetch_tracker = FetchCounter()
```
I think `mypy` and the code editors are smart enough to infer the type in this case.

2021-12-02 16:02 UTC, sechkova commented on tests/test_updater_consistent_snapshot.py
> +        targetpaths: list = test_case_data["targetpaths"]
```suggestion
        targetpaths: List[str] = test_case_data["targetpaths"]
```

2021-12-03 07:49 UTC, closed without merging

2021-12-03 10:38 UTC, kairoaraujo commented
I closed this PR to avoid too many unrelated commits to fix my mess in merging the _develop_ on top of _kairoaraujo:issue#1682/repository-simulator-fetch-tracker_ branch.
The above-linked PR will be taking over with all relevant information.