Add TargetFile.custom() documentation when building readthedocs
theupdateframework/tuf pull request #1749
Opened 2021-12-23 13:39 UTC by MVrachev

Note: This pr will be a draft until I have managed to built read the docs with 
`Targetfile.custom()` included

Fixes #1602

**Description of the changes being introduced by the pull request**:

Add the missing `Targetfile.custom()` property to the RTD documentation.
This property is not documented and is not visible in RTD documentation: 
I think it would be useful to expose as the "supported" way for a client app to read custom metadata for a target.

**Please verify and check that the pull request fulfills the following
requirements**:

- [ ] The code follows the [Code Style Guidelines](https://github.com/secure-systems-lab/code-style-guidelines#code-style-guidelines)
- [ ] Tests have been added for the bug fix or new feature
- [ ] Docs have been added for the bug fix or new feature

2021-12-23 16:28 UTC, MVrachev commented
I managed to add the `TargetFile.custom()` property in the RTD documentation.
Now I want to research how can I add information about the `custom` type: `Dict[str, Any]`.

2022-01-04 13:44 UTC, MVrachev commented
I realized I was mistaken about the `custom` property, it's both documented and type annotated.
The only question remaining is are we sure the `custom` type is `Any` or it's actually `Dict[str, Any]`?
@jku what do you think?

2022-01-04 13:46 UTC, MVrachev commented on tuf/api/metadata.py
> +        return self.unrecognized_fields.get("custom")
By adding a docstring to the property RTD noticed `custom` and documented it.

2022-01-05 07:57 UTC, jku commented
> The only question remaining is are we sure the `custom` type is `Any` or it's actually `Dict[str, Any]`?

I wouldn't object to either.

Specification (summarized by me):
> **CUSTOM**: An object.

Object is never defined but does seem to mean JSON object -- a dictionary with string keys -- so annotating it as such seems reasonable. There's probably no need for us to validate `custom` in deserialization though.

2022-01-05 08:10 UTC, jku requested changes

2022-01-05 08:10 UTC, jku commented on tuf/api/metadata.py
> +        """Contains additional information about the TargetFile instance"""
Hmm, let's try to provide something more actionable here for someone just reading the API: now it sounds like python-tuf provides this additional information.

Maybe something like:
```
    """Can be used to provide implementation specific data related to the
    target. python-tuf does not use or validate this data.
    """
```

2022-01-06 16:24 UTC, ivanayov commented
@jku A valid json in python works for boolean and number strings as well, so in that case `Dict` might not fit. On the other hand it would be a bit strange to attach such non-informative value to `TargetFile`, unless someone decides to use if for a  hacky implementation in a very specific corner-case. But should we still allow that or just consider it's useless and restrict to `Dict`? With the change it nicer to use, formally it's not `Any` anymore.

2022-01-06 16:44 UTC, MVrachev commented
> @jku A valid json in python works for boolean and number strings as well, so in that case Dict might not fit. On the other hand it would be a bit strange to attach such non-informative value to TargetFile, unless someone decides to use if for a hacky implementation in a very specific corner-case. But should we still allow that or just consider it's useless and restrict to Dict? With the change it nicer to use, formally it's not Any anymore.

You are correct that `custom` could be a `List` and `boolean`, `string` and an `int` as well.
We are not sure what it could be in this case even though `Dict` makes the most sense.
I removed the commit that changes the type annotation.

2022-01-07 08:46 UTC, jku approved these changes

2022-01-07 08:47 UTC, merged