Review and document ngclient exceptions
theupdateframework/tuf pull request #1787
Opened 2022-01-20 16:53 UTC by MVrachev

Fixes #1312

**Description of the changes being introduced by the pull request**:

I made a review on all files inside `tuf/ngclient` to see which of them
needs additions or changes in their function docstrings regarding
exceptions.

I didn't find any changes required inside the `request_fetcher.py`
and of course inside the config module.
Other than that multiple additions had to be made.

For `trusted_metadata_set.py` we had a discussion with Jussi that there is
no need to list each of the specific `RepositoryError`s one by one as
this is an internal module and this will only create a bigger
maintenance burden.

For `updater.py` we had discussions with Jussi and Lukas that we want to
document only those exceptions that could be potentially handled.
This means there is no point in documenting each of the `RepositoryError`s
or `DownloadError`s separately.

Finally, I added a little documentation for `download_bytes()` inside
`fetcher.py`, as it's naming, suggests it's not an internal function.

Signed-off-by: Martin Vrachev <mvrachev@vmware.com>

**Please verify and check that the pull request fulfills the following
requirements**:

- [ ] The code follows the [Code Style Guidelines](https://github.com/secure-systems-lab/code-style-guidelines#code-style-guidelines)
- [ ] Tests have been added for the bug fix or new feature
- [ ] Docs have been added for the bug fix or new feature

2022-01-20 16:56 UTC, MVrachev commented
@lukpueh can you investigate why still there are required CI builds for `python3.6`?

2022-01-21 08:42 UTC, kairoaraujo reviewed
IMHO the raise message is more straightforward than the docstring for ``RuntimeError`` in the functions.
But I'm still unable to get better suggestions (Sorry), maybe more detailed information as the raising messages?

2022-01-21 08:46 UTC, MVrachev commented
> IMHO the raise message is more straightforward than the docstring for `RuntimeError` in the functions. But I'm still unable to get better suggestions (Sorry), maybe more detailed information as the raising messages?

Do you mean that the rest of the documentation regarding exceptions in `Raises` is more straightforward than the one I have added for `RuntimeError`s?
Can you elaborate more on that?

2022-01-21 08:59 UTC, kairoaraujo commented
> Do you mean that the rest of the documentation regarding exceptions in `Raises` is more straightforward than the one I have added for `RuntimeError`s? Can you elaborate more on that?

What I mean is that messages raises are more straightforward than the one in the docstrings.
```python
raise RuntimeError("Cannot update timestamp after snapshot")
raise RuntimeError("Cannot update snapshot before timestamp")
raise RuntimeError("Cannot update snapshot after targets")
raise RuntimeError("Cannot load targets before snapshot")
raise RuntimeError("Cannot load targets before delegator")
```

Maybe it is my interpretation, but reading the raised messages (not the code logic) gives me more details than the documentation.

2022-01-21 09:13 UTC, lukpueh commented
> @lukpueh can you investigate why still there are required CI builds for `python3.6`?

Oh sure. I had to kick out the 3.6 checks in the branch protection rules.

2022-01-25 09:01 UTC, jku requested changes
I agree with the core choices here: figuring out if we really cover everything with the exceptions docstrings is _really_ hard but I couldn't find anything where I disagreed with you.

lefty some very nitpicky comments (which are really up to you), and then the one about writing the file: raising OSError feels wrong... I'd rather we skip the securesystemslib function call altogether.

2022-01-25 09:01 UTC, jku commented on tuf/ngclient/fetcher.py
> +            'max_length'.
indents?

2022-01-25 09:01 UTC, jku commented on tuf/ngclient/updater.py
> +                raise OSError() from e
this looks wrong too... if no-one objects loudly, I'd rather you just open the file and use `shutil.copyfileobj()` directly. I've made the case in more detail in #1761

2022-01-25 09:01 UTC, jku commented on tuf/ngclient/_internal/trusted_metadata_set.py
> +
nitpick: other files (like updater.py) do not use this empty line

2022-01-25 09:01 UTC, jku commented on tuf/ngclient/fetcher.py
> +              the file or an upper bound.
_very_ nitpick: there should be no reason for max_length to have two lines of docstring...

In general I'd like to to avoid filler words like "value representing X" when  something like "upper bound of data size in bytes" should do just fine

2022-01-27 12:24 UTC, MVrachev commented on tuf/ngclient/updater.py
> +                raise OSError() from e
Yes, you are correct.
I made those changes before submitting https://github.com/theupdateframework/python-tuf/pull/1799 where I use `shutil.copyfileobj()`.

2022-01-27 12:29 UTC, MVrachev commented on tuf/ngclient/fetcher.py
> +              the file or an upper bound.
I think it's a valuable comment. It's good to simplify our docstrings and I agree with you here.

2022-01-27 12:41 UTC, MVrachev commented
@jku can we merge this pr first and then https://github.com/theupdateframework/python-tuf/pull/1799?
As this pr and https://github.com/theupdateframework/python-tuf/pull/1799 touch updater.download_target() I want to make sure that after we merge both of the prs the correct exception docstring will be there.

2022-01-27 12:43 UTC, MVrachev commented
@jku can we merge this pr first and then https://github.com/theupdateframework/python-tuf/pull/1799?
As this pr and https://github.com/theupdateframework/python-tuf/pull/1799 touch updater.download_target() I want to make sure that after we merge both of the prs the correct exception docstring will be there.

2022-01-27 13:23 UTC, jku approved these changes
Looks good to me, thanks.

2022-01-27 13:28 UTC, lukpueh approved these changes

2022-01-27 13:28 UTC, merged