Ngclient docstrings improvement
theupdateframework/tuf pull request #1856
Opened 2022-02-10 16:14 UTC by ivanayov

This change unifies ngclient docstrings language, including wording and quoting. No major changes included, as docs look well-formed.

Fixes #1844

- [x] The code follows the [Code Style Guidelines](https://github.com/secure-systems-lab/code-style-guidelines#code-style-guidelines)
- [n/a] Tests have been added for the bug fix or new feature
- [n/a] Docs have been added for the bug fix or new feature

2022-02-11 09:52 UTC, lukpueh requested changes
Thanks a lot for the patch, @ivanayov. I left a few minor comments inline...

2022-02-11 09:52 UTC, lukpueh commented on tuf/ngclient/_internal/trusted_metadata_set.py
> +(``trusted_set[Root.type]``) or, in the case of top-level metadata, using the helper
line length

2022-02-11 09:52 UTC, lukpueh commented on tuf/ngclient/_internal/trusted_metadata_set.py
> +        """Returns iterator over all ``Metadata`` objects in ``TrustedMetadataSet``"""
line length

2022-02-11 09:52 UTC, lukpueh commented on tuf/ngclient/_internal/trusted_metadata_set.py
>          is allowed to not match timestamp meta version: TrustedMetadataSet will
```suggestion
        is allowed to not match timestamp meta version: ``TrustedMetadataSet`` will
```
--> line length

2022-02-11 09:52 UTC, lukpueh commented on tuf/ngclient/_internal/requests_fetcher.py
>      library.
Minor nit: According to our style guide, this should fit on one line. What about...
```suggestion
    """An implementation of ``FetcherInterface`` based on the requests library.
```
?

2022-02-11 09:52 UTC, lukpueh commented on tuf/ngclient/fetcher.py
> +        up to ``max_length``.
Minor nit: According to our style guide, this should fit on one line. Also, at first glance this could be read as if hitting max length would just stop the download, although it actually raises an exception, which is described below anyway. Maybe we can just say as we do in `download_bytes`?
```suggestion
        """Download file from given url.
```
?

2022-02-11 09:52 UTC, lukpueh commented on tuf/ngclient/fetcher.py
> +        up to ``max_length``.
Optional: If we do want to give any more info here, e.g. in a paragraph after the opening line, I'd probably mention that `download_file` should be used in a `with` block, to always release the allocated file resources even if download fails. (not a blocker for this PR).

2022-02-11 09:52 UTC, lukpueh commented on tuf/ngclient/fetcher.py
> +        up to ``max_length``.
Minor nit 2: Consider consistently wrapping `url` in double backticks in opening lines of all functions of this module

2022-02-11 09:52 UTC, lukpueh commented on tuf/ngclient/updater.py
> +            writable and it must contain a trusted ``root.json`` file
Not sure if we need to backtick-wrap file names? Maybe just quote...?
```suggestion
            writable and it must contain a trusted 'root.json' file
```

2022-02-11 13:30 UTC, ivanayov commented
Thank you @lukpueh ! Just pushed an update addressing your comments.

2022-02-14 10:47 UTC, lukpueh approved these changes

2022-02-14 11:13 UTC, lukpueh commented
Thanks for the quick updates, @ivanayov! Merging...

2022-02-14 11:13 UTC, merged