Fixed annotation for unrecognized_fields
theupdateframework/tuf pull request #1950
Opened 2022-04-11 17:26 UTC by abs007

Metadata API: Annotate 'unrecognized_fields' as Dict

Fixes #1938 

**Description of the changes being introduced by the pull request**:

Annotating as Mapping seems wrong as further changes to the content might 
be added in the code base. Hence, annotation changed to Dict. 

Signed-off-by: Abhisman Sarkar <abhisman.sarkar@gmail.com>

2022-04-12 12:44 UTC, jku requested changes
The code changes look good to me, thanks!

However, could I ask you to include the information you added to the PR (which also looks good) as the commit message? Current commit message is not informative: 
```
metadata.py updated

Signed-off-by: Abhisman Sarkar <abhisman.sarkar@gmail.com>
```

`git commit --amend` should allow you to modify the message (keep the signed-off-by!), and a force push should update the PR here

2022-04-12 17:04 UTC, abs007 commented
Hi, I made the changes.

2022-04-13 06:41 UTC, jku approved these changes

2022-04-13 07:11 UTC, jku commented
Thanks for the contribution, looks great! Merging now

2022-04-13 07:11 UTC, merged

2022-04-13 07:46 UTC, abs007 commented
Appreciate the feedback.