Add SECURITY.md
theupdateframework/tuf pull request #2098
Opened 2022-09-06 18:55 UTC by mnm678

Fixes #2096 

The text here is copied from the README for easier discovery. I'm happy to make any changes to this policy while we're looking at it.

2022-09-07 07:55 UTC, lukpueh requested changes
I suggest to remove the same text in README.md (prone to get out of sync) but keep the section and link to this new document.

2022-09-07 16:14 UTC, joshuagl reviewed
Added some suggestions to match the original formatting.

2022-09-07 16:14 UTC, joshuagl commented on README.md
> +See [SECURITY.md](https://github.com/theupdateframework/python-tuf/blob/develop/SECURITY.md)
Nit: I think it's nicer to use relative links to docs in the same repo?
```suggestion
See [SECURITY.md](SECURITY.md)
```

2022-09-07 16:14 UTC, joshuagl commented on SECURITY.md
> +    Steps to reproduce the issue.
```suggestion
* Description of the vulnerability.
* Steps to reproduce the issue.
```

2022-09-07 16:14 UTC, joshuagl commented on SECURITY.md
> +
```suggestion
Optionally, reports that are emailed can be encrypted with PGP. You should use PGP key fingerprint **E9C0 59EC 0D32 64FA B35F 94AD 465B F9F6 F8EB 475A**.

```

2022-09-07 16:14 UTC, joshuagl commented on SECURITY.md
> +Please do not use the GitHub issue tracker to submit vulnerability reports. The issue tracker is intended for bug reports and to make feature requests. Major feature requests, such as design changes
```suggestion
Please do not use the GitHub issue tracker to submit vulnerability reports. The issue tracker is intended for bug reports and to make feature requests. Major feature requests, such as design changes to the specification, should be proposed via a [TUF Augmentation Proposal](https://theupdateframework.github.io/specification/latest/#tuf-augmentation-proposal-tap-support) (TAP).
```

2022-09-08 08:10 UTC, lukpueh requested changes
Please fix DCO and consider changing document location. Otherwise LGTM.

2022-09-08 08:10 UTC, lukpueh commented on README.md
> +See [SECURITY.md](SECURITY.md)
Should we move `SECURITY.md` to `docs/`? All our `*.md` files are already there and[ GitHub will still find it](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository#about-security-policies):
  > To give people instructions for reporting security vulnerabilities in your project, you can add a SECURITY.md file to your repository's root, **docs**, or .github folder.

We'd have to adopt the change here...
```suggestion
See [SECURITY.md](docs/SECURITY.md)
```


 Related issue: #1849

2022-09-09 08:05 UTC, lukpueh approved these changes
Thanks, Marina!

2022-09-09 08:06 UTC, merged