Move (most of) Key to Securesystemslib
theupdateframework/tuf pull request #2165
Opened 2022-11-04 10:30 UTC by jku

Remove most of Key, and move it to Securesystemslib.

Let's dicuss in https://github.com/secure-systems-lab/securesystemslib/pull/456

2022-11-04 15:50 UTC, jku commented
Unsure what to do with the documentation: I don't want to reproduce the docs in python-tuf... but I don't know if we can import the Key docs from securesystemslib?

2022-11-04 15:55 UTC, lukpueh commented
>  but I don't know if we can import the Key docs from securesystemslib?

I think that's a good idea. It's what we for in-toto's key utilities:
https://in-toto.readthedocs.io/en/latest/api.html#key-utilities

2022-11-04 16:14 UTC, jku commented
> > but I don't know if we can import the Key docs from securesystemslib?
> 
> I think that's a good idea. It's what we for in-toto's key utilities: https://in-toto.readthedocs.io/en/latest/api.html#key-utilities

oh nice: we should be doing that for Signer and Signature as well -- basically for the "modern" securesystemslib api.

it's interesting how that autodoc magic seems to work without ever importing securesystemslib...

2022-11-11 16:08 UTC, jku commented
this is now out of date since I modified the securesystemslib PR -- it's still roughly correct, but I am not sure if a python-tuf Key is even needed anymore, maybe not. Will update next week

2022-11-25 12:11 UTC, jku commented on tox.ini
> +    python3 -m pip install --force-reinstall git+https://github.com/jku/securesystemslib.git@privkeyuri#egg=securesystemslib[crypto,pynacl]
this is testing leftover -- but it does lead to one passing test :champagne:

2022-11-30 15:26 UTC, lukpueh commented
Just tried out signing with post quantum keys (sphincs+) using the new signer API.  Works like a charm and out of the box! 🎉  cc @rugo 
<details>
<summary>see snippet</summary>

```bash
# Install `tuf` from this branch and `securesystemslib` from secure-systems-lab/securesystemslib#456
python3 -m pip install git+https://github.com/jku/python-tuf.git@no-key#egg=tuf
python3 -m pip install --force-reinstall git+https://github.com/jku/securesystemslib.git@privkeyuri#egg=securesystemslib[crypto,pynacl,PySPX]
```

POC: Verify that root metadata is signed by at least one sphincs+ key as required
```python
import os

from securesystemslib.keys import generate_sphincs_key
from securesystemslib.signer import Signer, SSlibKey, SSlibSigner

from tuf.api.metadata import Metadata, Root

# Generate pq keys
pq_key = generate_sphincs_key()
pq_pubkey = SSlibKey.from_securesystemslib_key(pq_key)
pq_signer = SSlibSigner(pq_key)

# # Generic solution: Use `Signer.from_priv_key_uri` instead of `SSlibSigner`,
# #     this also works:
#
# os.environ["PQ_KEY"] = pq_key["keyval"]["private"]
# pq_signer = Signer.from_priv_key_uri("envvar:PQ_KEY", pq_pubkey)

# Generate root role and configure signature requirement
root = Root()
root.add_key(pq_pubkey, Root.type)

# Wrap root in metadata envelope and add signature
root_metadata = Metadata(root)
root_metadata.sign(pq_signer)

# Assert `verify_delegate` indeed needs at least one sig from above key
assert root_metadata.signed.roles["root"].threshold == 1
assert root_metadata.signed.roles["root"].keyids == [pq_pubkey.keyid]

root_metadata.verify_delegate(Root.type, root_metadata)
```

</details>

2022-12-01 08:36 UTC, jku commented
Current state:
* Works with securesystemslib master
* Should not be merged before there is a securesystemslib release (and we start depending on it)
* the main commit really should be split into a few separate ones
* the `verify_delegate()` refactor needs a good review

2022-12-01 13:17 UTC, jku commented
Ok, PR is ready for review I think -- not for merge though, we do need a securesystemslib release before that. Updated description

2023-01-12 13:41 UTC, jku commented
Rebased

2023-01-17 13:19 UTC, jku commented
Rebased and then added a commit to fix #2272

2023-01-17 13:29 UTC, jku commented
Rebased and then added 
* commit to fix #2272
* one more fix to key usage in examples

2023-01-18 16:40 UTC, jku commented
TODO: Package should depend on securesystemslib >= 0.26 now

2023-01-27 12:12 UTC, lukpueh requested changes
> TODO: Package should depend on securesystemslib >= 0.26 now

I think this is the only thing that's missing.

Otherwise LGTM. 👍

2023-01-31 08:20 UTC, lukpueh approved these changes
Thanks!

2023-01-31 08:20 UTC, merged