Moved lint to seperate job. Some refactor as well.
theupdateframework/tuf pull request #2317
Opened 2023-03-02 19:04 UTC by shabeebk

Please fill in the fields below to submit a pull request.  The more information
that is provided, the better.

Fixes #1248 

**Description of the changes being introduced by the pull request**:
The CI pipeline has been changed to run the lint tasks in the first and fail if the lint job fails.

**Please verify and check that the pull request fulfills the following
requirements**:

- [x] The code follows the [Code Style Guidelines](https://github.com/secure-systems-lab/code-style-guidelines#code-style-guidelines)
- [ ] Tests have been added for the bug fix or new feature
- [ ] Docs have been added for the bug fix or new feature

2023-03-02 19:09 UTC, shabeebk commented
@lukpueh @jku, thanks for spending time reviewing the works :+1:. I have got a new PR with cleaner commits and signoff. Please review. The requirement is achieved and the suggestions are taken care of.

2023-03-03 08:55 UTC, lukpueh commented
FYI: You wouldn't have needed to submit new PRs for a cleaner git history. You can change your git history locally, e.g. using `git rebase`, and then force push to your remote branch, e.g. `git push origin issue-1248-2 -f`.

Our [git history guideline doc](https://github.com/secure-systems-lab/lab-guidelines/blob/master/git-history.md) talks a bit about rebasing on an open PR, and has some pointers to good further reading.

2023-03-03 09:07 UTC, lukpueh requested changes
Thanks! I left a few more suggestions. Please accept, and we can merge.

2023-03-03 09:07 UTC, lukpueh commented on .github/workflows/_test.yml
> +      # sslib-master on Linux/Python3.x only.
Looks like you undid this change we merged in yesterday via #2315, while resolving a conflict? Please change back:
```suggestion
      # (sslib main) on Linux/Python3.x only.
```

2023-03-03 09:07 UTC, lukpueh commented on .github/workflows/_test.yml
> +      TOXENV: lint
You can also configure toxenv via command line argument, then you don't need to set an envvar.
```suggestion
```

2023-03-03 09:07 UTC, lukpueh commented on .github/workflows/_test.yml
> +        run: tox
You can also configure toxenv via command line argument, then you don't need to set an envvar.
```suggestion
      - name: Run tox
        run: tox -e lint
```

2023-03-03 09:07 UTC, lukpueh commented on .github/workflows/_test.yml
> +    continue-on-error: ${{ matrix.failure-allowed }}
No need to use a variable here, if it always has the same value
```suggestion
    continue-on-error: true
```

2023-03-03 09:07 UTC, lukpueh commented on .github/workflows/_test.yml
> +        failure-allowed: [true]
No need to use a variable here, if it always has the same value
```suggestion
```

2023-03-03 09:07 UTC, lukpueh commented on .github/workflows/_test.yml
> +            failure-allowed: true
No need to use a variable here, if it always has the same value
```suggestion
```

2023-03-03 18:39 UTC, shabeebk commented
@lukpueh, accepted. All look good to me. :+1:

2023-03-06 10:26 UTC, lukpueh approved these changes
LGTM, thanks!

2023-03-06 10:26 UTC, merged