Move verify_delegate() to Root/Targets
theupdateframework/tuf pull request #2378
Opened 2023-05-05 07:39 UTC by jku

Fixes #2361 

**Description of the changes being introduced by the pull request**:

* Add an internal `_Delegator` class that implements verify_delegate()
* Inherit that class in Root, Targets: the internal class is just an implementation detail for sharing the implementation, not something users of the library should care about
* Document Metadata.verify_delegate() as deprecated
* Use the new method in tests, examples and ngclient

This will make both ngclient and external repository code slightly easier to read and write (but note that the ngclient cleanups are not included here as they touch quite a lot of lines even if they are simple).

There are several ways to add verify_delegate() to Root and Targets, I think this helper class is a decent compromise between modularity and simplicity: 
* the _Delegator class isn't intended to be part of a longer "inheritance path": it just provides an extra method for Root and Targets. If there's a naming style for this style of inheritance I'm happy to use it
*_Delegator is internal: users of the library don't need to care about it

**Please verify and check that the pull request fulfills the following
requirements**:

- [x] The code follows the [Code Style Guidelines](https://github.com/secure-systems-lab/code-style-guidelines#code-style-guidelines)
- [x] Tests have been added for the bug fix or new feature
- [x] Docs have been added for the bug fix or new feature

2023-05-05 09:56 UTC, jku commented
> If there's a naming style for this style of inheritance I'm happy to use it

A "Mixin" is likely what I'm trying to remember here?

2023-05-10 07:17 UTC, jku commented
I think this is ready for review. I have a branch [cleanup-after-verify-delegate-move](https://github.com/jku/python-tuf/commits/cleanup-after-verify-delegate-move) with changes based on this PR... but they are not required so I'll do those separately.

2023-05-10 07:21 UTC, jku commented on tuf/api/metadata.py
> +        Raises ValueError if key is not found.
this change just makes the two implementations have the same docstring.

2023-05-10 07:57 UTC, jku commented on tuf/api/metadata.py
> +    ) -> None:
Maybe a meaningful note here is that this makes `Targets` and `Root` "aware" of `Metadata` now.

The alternative would be for the arguments to include payload bytes and signatures so something like 

    def verify_delegate(
        self,
        delegated_role: str,
        payload: bytes,
        signatures: Dict[str, Signature]
    )

Unfortunately I'm not sure how one would make that usable in calling code

2023-05-12 08:58 UTC, lukpueh requested changes
This change makes sense. I pointed out some nits that you may ignore. The only thing that should be changed is `test_api.TestMetadata.test_metadata_verify_delegate`, which still uses `Metadata.verify_delegate`. Otherwise, the tests pass even without that method.

Also, I think the version number in the deprecation notice is wrong (see inline comment).

2023-05-12 08:58 UTC, lukpueh commented on tuf/api/metadata.py
> +        .. deprecated:: 2.2.0
Is this the correct version number?

2023-05-12 08:58 UTC, lukpueh commented on tuf/api/metadata.py
> +        threshold of keys for the delegated role ``delegated_role``.
Off-topic and not important, but here's a chance for leaner docs, which also makes it consistent with the first part of the sentence.
```suggestion
        threshold of keys for the ``delegated_role``.
```

2023-05-12 08:58 UTC, lukpueh commented on tuf/api/metadata.py
> +        Raises ValueError if key is not found.
You could actually remove docstrings for `get_key` and `get_delegated_role` in `Targets` and `Root`, since they can be reused from their definitions in the parent class. Pylint would need to be told to not complain. So maybe not worth it, the docstrings are short enough.

2023-05-12 08:58 UTC, lukpueh commented on tests/test_api.py
> +    # pylint: disable=too-many-locals,too-many-statements
I think this disables pylint downwards on class scope and not on function scope. Probably not what you intended, but also no big deal.

2023-05-12 13:02 UTC, jku commented on tuf/api/metadata.py
> +        Raises ValueError if key is not found.
I was sure that wouldn't work with sphinx but I tried and you are right.

2023-05-15 08:12 UTC, jku commented
> `test_api.TestMetadata.test_metadata_verify_delegate`, which still uses `Metadata.verify_delegate`

I left a small test in place to make sure I didn't break that one -- just enough testing to make sure it's connected to the actual implementation in Signed. 

`test_signed_verify_delegate()` contains all of the tests that existed before.

2023-05-15 08:28 UTC, jku commented
```
ERROR: /home/runner/work/python-tuf/python-tuf/verify_release Imports are incorrectly sorted and/or formatted.
--- /home/runner/work/python-tuf/python-tuf/verify_release:before	2023-05-15 08:14:43.101068
+++ /home/runner/work/python-tuf/python-tuf/verify_release:after	2023-05-15 08:15:05.396047
@@ -19,9 +19,8 @@
 from typing import Optional
 
 try:
+    import build as _
     import requests
-
-    import build as _
 except ImportError:
     print("Error: verify_release requires modules 'requests' and 'build':")
     print("    pip install requests build")
lint: exit 1 (0.27 seconds) /home/runner/work/python-tuf/python-tuf> isort --check --diff tuf examples tests verify_release pid=1912
```

The code that is failing on CI is exactly the code that my isort is suggesting I use.

Same exact isort version
 
 (╯°□°)╯︵ ┻━┻

2023-05-15 08:36 UTC, jku commented
I've dropped the commit that would make lint work on my machine... CI doesn't seems to mind :shrug: 

Let's maybe not merge this yet though: I still feel like we might be designing ourselves into a corner wrt DSSE.

Marking draft while thinking about it...

2023-08-01 14:16 UTC, lukpueh commented
> The alternative would be for the arguments to include payload bytes and signatures so something like
> 
> ```
> def verify_delegate(
>     self,
>     delegated_role: str,
>     payload: bytes,
>     signatures: Dict[str, Signature]
> )
> ```
> 
> Unfortunately I'm not sure how one would make that usable in calling code

I have a patch for this on top of your (rebased) branch. It also adds an alias for default canonical signed bytes to Metadata. This makes the calling code only slightly more complicated: https://github.com/theupdateframework/python-tuf/compare/635a2870bde3c44b4eab9e66be61c77e08e47285...lukpueh:move-verify-delegate-v2

I think this is a reasonable path towards #2385. @jku, feel free to take over my branch for this PR, or let me know if you want me to force push.

2023-08-16 09:51 UTC, lukpueh approved these changes

2023-08-16 09:52 UTC, lukpueh commented
@jku, you may want to approve this pr too, now that it's a collaboration.

2023-08-21 11:08 UTC, jku commented
It looks like original author cannot click "approve"... but I think this looks correct and reasonable.

2023-08-21 11:27 UTC, merged