Enhancing The Update Framework (Python - TUF) README
theupdateframework/tuf pull request #2655
Opened 2024-06-08 19:10 UTC by shubhusion

**Description of the changes being introduced by the pull request**:

1. **Table of Contents**: Added a Table of Contents to improve navigation and accessibility within the README.
   
2. **Logo Color**: Changed the logo color from black to white to enhance visibility and improve the overall aesthetic of the document.
   
3. **Additional Badges**: Included additional badges to highlight key aspects such as version, license, tech-stack, and community support, providing users with quick access to essential information.
   
4. **Back to Top Button**: Added a "Back to Top" button at the bottom of the README to facilitate easy navigation within the document.
   
5. **Installation Section**: Added an Installation section to provide users with clear guidance on how to install the software.

6. **Contact Section Enhancement**: Separated the Mailing List and CNCF Slack links for better readability and organization within the Contact section.

7. **CNCF Logo Addition**: Added the CNCF logo at the bottom of the README to acknowledge the project's affiliation with the Cloud Native Computing Foundation.

**Before:**
![image](https://github.com/theupdateframework/python-tuf/assets/96301987/cebd9a21-26b3-4729-adeb-a5746dc916c9)

**After:**
![image](https://github.com/theupdateframework/python-tuf/assets/96301987/3c9e83ac-67a1-461b-988f-bd79d9c7de35)

Fixes #2654

2024-06-09 19:23 UTC, shubhusion commented
@trishankatdatadog please review this PR for the issue #2654

2024-06-17 06:53 UTC, jku commented
> 2\. **Logo Color**: Changed the logo color from black to white to enhance visibility and improve the overall aesthetic of the document.

This change makes the logo invisible with default GitHub Settings (You are using dark theme on GitHub so see the opposite effect).

2024-06-17 07:58 UTC, shubhusion commented
> > 2. **Logo Color**: Changed the logo color from black to white to enhance visibility and improve the overall aesthetic of the document.
> 
> This change makes the logo invisible with default GitHub settings (You are using dark theme on GitHub so see the opposite effect).

To ensure the logo is visible in both light and dark themes, a solution that automatically switches the logo based on the user's selected theme preference can be implemented. This strategy involves utilizing two different logo versions (one for light theme and one for a dark theme) and utilizing HTML and CSS to manage the theme-based switching.

2024-06-17 10:25 UTC, shubhusion commented
@jku it works for both light and dark theme now. please have a look

2024-06-17 11:22 UTC, jku requested changes
I've not looked at the text content changes(would appreciate someone else having a look). 

Structural changes look nice (like use of actual headers) but I left comments on the urls etc

2024-06-17 11:22 UTC, jku commented on README.md
> +</picture>
* alt text is incorrect
* I don't think you need to specify `source` for light theme: the default `img` is enough
* I think linking to pngs in cncf/artwork project would be totally fine, even preferable: if you do want to upload the pngs to this project then
   * please don't put them directly in the root directory
   * `https://github.com/shubhusion/python-tuf/` is not ok as url

2024-06-17 11:22 UTC, jku commented on README.md
> +[![License: Apache 2.0](https://img.shields.io/badge/License-Apache%202.0-blue.svg)](https://opensource.org/licenses/Apache-2.0)
These links are already provided by github as clickable tabs just a few cm above this.

2024-06-17 11:22 UTC, jku commented on README.md
> +- [Acknowledgements](#acknowledgements)
GitHub already provides an automatic  TOC in the tab bar now that you've added headers. I have to wonder if that would be enough (considering that one requires 0 maintenance)

2024-06-17 11:22 UTC, jku commented on README.md
> +---
Now that you are using headers (good idea), I think these horizontal lines are just clutter: I think most of them can just be removed

2024-06-17 11:22 UTC, jku commented on README.md
> +
This duplicates functionality people already have in their browsers, except now we have to maintain that functionality. Let's not add things like this.

2024-07-23 21:41 UTC, trishankatdatadog commented
> @trishankatdatadog @JustinCappos please review this PR for the issue #2654

Sorry, I'm running out of B/W... please try someone else? @jku has been massively helpful here, thanks!

2024-07-24 08:38 UTC, lukpueh commented
@jku already left a thorough review here. From what I see, the key improvement of this PR is to use the correct markup for the section headers. @shubhusion, do you plan to address the review comments?

2024-07-27 18:41 UTC, shubhusion commented
> @jku already left a thorough review here. From what I see, the key improvement of this PR is to use the correct markup for the section headers. @shubhusion, do you plan to address the review comments?

@lukpueh yeah I will make changes as specified

2024-08-19 07:08 UTC, jku requested changes
* There are now unused pngs included in the PR: please remove those
* There are some issues with the CNCF section at the bottom, left a comment there

**Note to PR merger**: If the pngs are in any commit in the PR, this should be squash merged to prevent them from being part of git history

2024-08-19 07:08 UTC, jku commented on README.md
> +</div>
* links to "https://github.com/shubhusion/ are still not ok
* I also wonder if CNCF really needs a second level title and a huge logo in addition to the acknowledgement it already had. We could just tweak the previous CNCF reference in "Acknowledgements" to include the mention of being a graduated project?

2024-10-22 07:37 UTC, jku commented
I'm closing this since no action in 2 months. 

Please reopen if you get to it at a later date

2024-10-22 07:37 UTC, closed without merging