Fix publishing of coverage results to coveralls.io (+ misc test config updates)
theupdateframework/tuf pull request #890
Opened 2019-06-25 15:17 UTC by lukpueh

**Fixes issue #**:
None

**Description of the changes being introduced by the pull request**:
Code coverage results from our Travis builds have not been published to coveralls.io in a while, due to the required `coveralls` publishing tool not being properly installed. 

Besides fixing publishing of coverage results, this PR cleans up/ updates other testing configurations:
 - Update travis to run on xenial
 - Add a build matrix to run each tox env in a corresponding travis env as per travis/tox best practices.
      https://docs.travis-ci.com/user/languages/python/#using-tox-as-the-build-script
 - Enable Python 3.5 tests, after all we claim to support Python 3.5
 - Remove "only build certain branch" restrictions
 - Use "install" instead of "before_script"  to install dependencies.
    Explicitly listing "install" prevents Travis from automatically running `pip install -r requirements.txt`, which is not necessary because most of those requirements are installed again in each  tox environment.
 - Move pylint and bandit calls to tox (pylint requires  dependencies) to be installed.

**Please verify and check that the pull request fulfills the following
requirements**:

- [ ] The code follows the [Code Style Guidelines](https://github.com/secure-systems-lab/code-style-guidelines#code-style-guidelines)
- [ ] Tests have been added for the bug fix or new feature
- [ ] Docs have been added for the bug fix or new feature

2019-06-25 15:27 UTC, lukpueh commented
**WIP! don't merge!**

2019-06-27 09:09 UTC, lukpueh commented
Fixed! See most recent [Travis builds](https://travis-ci.org/theupdateframework/tuf/builds/550904748?utm_source=github_status&utm_medium=notification) and corresponding [coverage reports on coveralls](https://coveralls.io/builds/24224525).

The badge on the main README should be updated once this PR is merged and IIUC we will see GitHub status (as in the table above) in subsequent PRs, because coveralls needs a reference build.

2019-06-27 11:07 UTC, lukpueh commented
See most recent [Travis builds](https://travis-ci.org/secure-systems-lab/securesystemslib/builds/551256979?utm_source=github_status&utm_medium=notification) and corresponding [coverage reports on coveralls](https://coveralls.io/builds/24241109).

The badge on the main README should be updated once this PR is merged and IIUC we will see GitHub status (as in the table at the bottom) in subsequent PRs, because coveralls needs a reference build.

2019-07-08 17:09 UTC, tanishqjasoria approved these changes
I went through the PR and it looks good to me!

2019-09-10 21:28 UTC, adityasaky requested changes

2019-09-10 21:28 UTC, adityasaky commented on .travis.yml
> +  # as the convention.
*is

2019-09-11 09:41 UTC, merged

2019-09-11 09:42 UTC, lukpueh commented
Thanks, @adityasaky!