Bump version 0.12.0-dev0
theupdateframework/tuf pull request #921
Opened 2019-09-20 16:03 UTC by lukpueh

1. Wait for securesystemslib 0.12.0 to be released on PyPI
1. Merge #917 and #918 to adapt to breaking changes in securesystemslib
1. Rebase this release PR onto develop
1. Release tuf 0.12.0-dev0
*Alternatively, and if preferred, release as 1.0.0-dev0 instead (requires changing the version numbers in `CHANGELOG.md`, `setup.py` and `__init__.py`)*

2019-10-03 11:49 UTC, lukpueh commented
Update:
The TUF team has decided that the next release will be `0.12.0` (w/o `dev` suffix), under the condition that we add a disclaimer about TUF's currently limited protection against slow retrieval attacks. See https://github.com/theupdateframework/tuf/pull/928 for a proposal. (cc @trishankatdatadog, @JustinCappos @mnm678 )

2019-10-03 12:14 UTC, JustinCappos commented on setup.py
> +  version = '0.12.0-dev0', # If updating version, also update it in tuf/__init__.py
```suggestion
  version = '0.12.0', # If updating version, also update it in tuf/__init__.py
```

2019-10-03 12:15 UTC, JustinCappos requested changes
Need to change these version strings, right?

2019-10-03 12:15 UTC, JustinCappos commented on tuf/__init__.py
> +__version__ = "0.12.0-dev0"
```suggestion
__version__ = "0.12.0"
```

2019-10-03 12:17 UTC, lukpueh commented
@JustinCappos, yes absolutely. Thanks for the reminder! I would have done it, when rebasing to integrate a merged #928.

2019-10-03 12:18 UTC, lukpueh commented on docs/CHANGELOG.md
> +## v0.12.0-dev0
Remove `-dev0`

2019-10-03 12:52 UTC, lukpueh commented
@trishankatdatadog wants to get #885 in before we bump to 0.12.0. #885 is already finished and reviewed. All that's missing is a test.

2019-10-14 17:37 UTC, JustinCappos approved these changes
LGTM

2019-10-14 17:59 UTC, trishankatdatadog approved these changes
💯, @lukpueh is the man

2019-10-14 19:52 UTC, merged