Add disclaimer about limited slow retrieval attack protection
theupdateframework/tuf pull request #928
Opened 2019-10-03 11:43 UTC by lukpueh

**Fixes issue #**:
None. Related to #781.

**Description of the changes being introduced by the pull request**:
Since https://github.com/theupdateframework/tuf/pull/781 we only provide limited protection against slow retrieval attacks. So far this has only been discussed in above issue and hinted at by a disabled test and a code comment in that test.

This change adds a corresponding disclaimer to a more prominent place, i.e. the list of attacks in SECURITY.md.

**Please verify and check that the pull request fulfills the following
requirements**:

- [ ] The code follows the [Code Style Guidelines](https://github.com/secure-systems-lab/code-style-guidelines#code-style-guidelines)
- [ ] Tests have been added for the bug fix or new feature
- [ ] Docs have been added for the bug fix or new feature

2019-10-03 12:01 UTC, lukpueh commented
We may also want to exclude (or add a comment to) the section about slow retrieval attacks in the tutorial-like ATTACKS.md document.

2019-10-03 17:34 UTC, trishankatdatadog requested changes

2019-10-03 17:34 UTC, trishankatdatadog commented on docs/SECURITY.md
> +**_NOTE: The TUF reference implementation currently provides only limited protection against slow retrieval attacks (see [tuf#781](https://github.com/theupdateframework/tuf/pull/781))._**
```suggestion
**_NOTE: Due to limitations in a 3rd-party HTTP library, the TUF reference implementation currently provides only limited protection against slow retrieval attacks (see [tuf#781](https://github.com/theupdateframework/tuf/pull/781)). We plan to fix this in a future release._**
```

2019-10-03 17:35 UTC, trishankatdatadog commented
Thanks, @lukpueh! Just want to make it clearer that this limitation is not due to our code...

2019-10-03 21:29 UTC, JustinCappos commented on docs/SECURITY.md
> +**_NOTE: The TUF reference implementation currently provides only limited protection against slow retrieval attacks (see [tuf#781](https://github.com/theupdateframework/tuf/pull/781))._**
Should we be trying to fix this upstream in request?  Is that sensible?  If so, should we link to that discussion instead?

The issue we refer to here has a lot going on, I'd prefer we had something clearer to point to.

2019-10-03 21:45 UTC, trishankatdatadog commented on docs/SECURITY.md
> +**_NOTE: The TUF reference implementation currently provides only limited protection against slow retrieval attacks (see [tuf#781](https://github.com/theupdateframework/tuf/pull/781))._**
Yeah, I guess we should at least file an issue that points to slow loris attacks.

2019-10-10 14:51 UTC, lukpueh commented
I created an issue #932 (downstream for the time being) that summarizes key points from #781 and updated the disclaimer in this PR. Please review/approve/merge.

 I think this is the last thing we wanted to get in before bumping tuf to 0.12.0 (https://github.com/theupdateframework/tuf/pull/921).

2019-10-10 16:59 UTC, mnm678 approved these changes
LGTM

2019-10-10 18:39 UTC, JustinCappos commented
Is the failing test a race condition / Heisenbug?  I would merge otherwise

2019-10-11 07:43 UTC, lukpueh commented
> Is the failing test a race condition / Heisenbug? I would merge otherwise

It's a timeout issue, which seems to happen fairly often for tests on appveyor/windows (less often on travis/linux too). In any case, the fail here is impossibly related to the change in this PR. I say it's safe to merge.

2019-10-11 07:43 UTC, merged